feat: add docker support
craftycodie/Xenia-WebServices pull request #3
Opened 2023-03-10 15:54 UTC by JefvdA

I added a `Dockerfile` and `docker-compose.yaml`.

I almost never install software locally, and thus I added docker support for your project. If this is not something you want, no worries. Also if something is not clear, or you want me to change something before implementing the changes, let me know.

2023-03-10 16:33 UTC, craftycodie requested changes

2023-03-10 16:33 UTC, craftycodie commented
Just a nit-pick, other than that it looks. great! Thank you :)

2023-03-10 16:36 UTC, JefvdA commented
> Just a nit-pick, other than that it looks. great! Thank you :)

Nono, no nit-pick. I forgot to ask this as well, as I was not sure what version to use. I'll change it 👍

2023-03-10 16:39 UTC, craftycodie commented
I had no idea mongo-express was a thing, looks useful.

2023-03-10 17:17 UTC, SarahGreyWolf commented on docker-compose.yaml
> +    image: mongo
It's not ideal but making mongo use version 4.4.6 will allow it to run on ARM64/v8 systems like the raspberry pi 4.
Any newer version than that doesn't work thanks to mongo targeting a slightly newer ARM64/v8 architecture than these devices

2023-03-10 18:15 UTC, craftycodie requested changes
Please update the readme to explain docker setup, doesn't have to be too in-depth :)

2023-03-11 02:46 UTC, SarahGreyWolf commented
The Dockerfile doesn't really seem necessary at all since you never use nest-cli.
Also running stuff in containers using commands is not really the right way to use docker, it should be mostly contained within the Dockerfile for the image, with stuff in docker-compose used for configuring the app.

2023-03-11 11:12 UTC, JefvdA commented on Dockerfile
> +FROM node:19.7-alpine AS builder
I've updated the Dockerfile to now use the LTS version 18.15

2023-03-11 11:16 UTC, JefvdA commented
> This is currently missing the required `MONGO_URI` variable

You're right, the node service shouldn't rely on the `MONGO_URI` from within the .env file. I added this variable to the node service, and set the `MONGO_URI` to the uri of the mongo container.

2023-03-11 11:37 UTC, JefvdA commented on docker-compose.yaml
> +    image: mongo
I updated the docker-compose to now use mongo version 4.4.6. Do you think I should change versions of other docker images aswell, I am not quite sure if they support ARM64/v8 architecture aswell

2023-03-11 12:20 UTC, craftycodie commented on Dockerfile
> +FROM node:19.7-alpine AS dev
Is this used?

2023-03-11 12:23 UTC, JefvdA commented on Dockerfile
> +FROM node:19.7-alpine AS dev
Sarah said this aswell, but the nest-cli is used for starting the server, that's why I included it. I don't know why I installed it globally tho, as it's actually in the `devDependencies` aswell. I'll see if I can just ditch the Dockerfile all together.

2023-03-11 12:36 UTC, JefvdA commented on Dockerfile
> +FROM node:19.7-alpine AS dev
This is the reason I added the Dockerfile with the global install for `nest-cli` was because `npm run start` uses nest to start the application. The problem is that if you use `nest start` as a command, you will need the nest-cli installed locally. I updated the docker-compose to now use the local installation of the nest-cli instead, this way I can just remove the Dockerfile. 

Previous start command: `npm run start`
New start command: `node_modules/.bin/nest start`

2023-03-11 12:39 UTC, JefvdA commented
> The Dockerfile doesn't really seem necessary at all since you never use nest-cli. Also running stuff in containers using commands is not really the right way to use docker, it should be mostly contained within the Dockerfile for the image, with stuff in docker-compose used for configuring the app.

You were right about the Dockerfile, I removed the commands depending on a global install of `nest-cli` and thus was able to remove the Dockerfile. [the conversation](https://github.com/craftycodie/Xenia-WebServices/pull/3#discussion_r1133078881)

As for the commands being ran in the containers, is now needed because I removed the Dockerfile. Do you think I should re-add the Dockerfile, so that I can remove the commands from the docker-compose?

2023-03-12 01:03 UTC, Margen67 commented on docker-compose.yaml
> +      - main
End of file newline

2023-03-12 10:49 UTC, closed without merging